// mobile/utils/tts_loud.ts
import { Audio } from "expo-av";
import Constants from "expo-constants";

import { TtsEmphasis, TtsGender } from "./voiceStore";

export type VoiceStyle = "calm" | "warning";
export type VoiceOptions = {
  voice?: string;
  gender?: TtsGender;
  style?: VoiceStyle;
  emphasis?: TtsEmphasis;
  pauseMs?: number;
  volume?: number;
  lang?: "fil" | "en";
};

let currentSound: Audio.Sound | null = null;
let lastStartAt = 0;
let playbackModeReady = false;
let lastRequestSignature = "";
let lastRequestAt = 0;
let activeSpeakToken = 0;
const isDev = Boolean((globalThis as any).__DEV__);
let inFlightSpeakCount = 0;

// Generated by GitHub Copilot
/**
 * Debug-only state snapshot for diagnosing overlapping TTS requests.
 */
export function getTtsDebugState() {
  return {
    inFlightSpeakCount,
    hasCurrentSound: Boolean(currentSound),
    activeSpeakToken,
    lastStartAt,
    lastRequestAt,
  };
}

export async function stopSpeakLoud(invalidatePending = true) {
  // Generated by GitHub Copilot
  // Invalidate in-flight requests so stale createAsync calls cannot start playing later.
  if (invalidatePending) {
    activeSpeakToken += 1;
  }

  if (!currentSound) return;

  try {
    await currentSound.stopAsync();
  } catch {}

  try {
    await currentSound.unloadAsync();
  } catch {}

  currentSound = null;
}

async function forcePlaybackMode() {
  if (playbackModeReady) return;

  await Audio.setAudioModeAsync({
    allowsRecordingIOS: false,
    playsInSilentModeIOS: true,
    staysActiveInBackground: false,
    shouldDuckAndroid: false,
    playThroughEarpieceAndroid: false,
  });

  playbackModeReady = true;
}

export async function speakLoud(text: string, options?: VoiceOptions) {
  inFlightSpeakCount += 1;

  try {
    const cleanedText = (text || "").trim();
    if (!cleanedText) return;

    const now = Date.now();
    const signature = [
      cleanedText,
      options?.voice ?? "",
      options?.gender ?? "female",
      options?.style ?? "calm",
      options?.emphasis ?? "medium",
      String(options?.pauseMs ?? 280),
      options?.lang ?? "fil",
    ].join("|");

    // Generated by GitHub Copilot
    // Ignore rapid duplicate requests so active speech does not get interrupted.
    if (signature === lastRequestSignature && now - lastRequestAt < 1800) {
      if (isDev) {
        console.debug("[tts_loud] duplicate request ignored", {
          elapsedMs: now - lastRequestAt,
          preview: cleanedText.slice(0, 64),
        });
      }
      return;
    }

    // Generated by GitHub Copilot
    // Guard before stopSpeakLoud(): avoid cutting off current audio for near-simultaneous requests.
    if (now - lastStartAt < 250) {
      if (isDev) {
        console.debug("[tts_loud] throttled request ignored", {
          elapsedMs: now - lastStartAt,
          preview: cleanedText.slice(0, 64),
        });
      }
      return;
    }

    lastRequestSignature = signature;
    lastRequestAt = now;

    // Generated by GitHub Copilot
    // Mark this request as the newest; older in-flight requests will self-cancel.
    const requestToken = ++activeSpeakToken;

    await stopSpeakLoud(false);

    // Generated by GitHub Copilot
    // Another request took over while we were stopping audio.
    if (requestToken !== activeSpeakToken) return;

    lastStartAt = now;

    const voice = options?.voice;
    const gender = options?.gender ?? "female";
    const style = options?.style ?? "calm";
    const emphasis = options?.emphasis ?? "medium";
    const pauseMs = options?.pauseMs ?? 280;
    const volume = options?.volume ?? 1.0;
    const lang = options?.lang ?? "fil";

    const baseUrl =
      Constants.expoConfig?.extra?.API_BASE_URL ??
      "https://tara-ai-backend-swbp.onrender.com";

    const params = new URLSearchParams({
      lang,
      gender,
      style,
      emphasis,
      pause_ms: String(Math.max(80, Math.min(650, Math.round(pauseMs)))),
      text: cleanedText,
    });

    if (voice) {
      params.set("voice", voice);
    }

    const url = `${baseUrl}/tts?${params.toString()}`;

    if (isDev) {
      console.debug("[tts_loud] playback start", {
        preview: cleanedText.slice(0, 64),
      });
    }

    // very important for iPhone loud playback after recording
    await forcePlaybackMode();

    const { sound } = await Audio.Sound.createAsync(
      { uri: url },
      {
        shouldPlay: true,
        volume,
        progressUpdateIntervalMillis: 200,
      }
    );

    // Generated by GitHub Copilot
    // Drop stale audio if a newer request arrived while this sound was loading.
    if (requestToken !== activeSpeakToken) {
      await sound.unloadAsync().catch(() => {});
      return;
    }

    currentSound = sound;

    sound.setOnPlaybackStatusUpdate((status: any) => {
      if (requestToken !== activeSpeakToken) return;

      const s = status;

      if (!s?.isLoaded) {
        if (s?.error) {
          console.warn("Audio playback error:", s.error);
        }
        return;
      }

      if (s.didJustFinish) {
        sound.unloadAsync().catch(() => {});
        if (currentSound === sound) currentSound = null;
      }
    });
  } catch (e) {
    console.warn("speakLoud failed:", e);
  } finally {
    inFlightSpeakCount = Math.max(0, inFlightSpeakCount - 1);
  }
}