// mobile/utils/tts_loud.ts
import { Audio } from "expo-av";
import Constants from "expo-constants";

import { TtsEmphasis, TtsGender } from "./voiceStore";

export type VoiceStyle = "calm" | "warning";
export type VoiceOptions = {
  voice?: string;
  gender?: TtsGender;
  style?: VoiceStyle;
  emphasis?: TtsEmphasis;
  pauseMs?: number;
  volume?: number;
  lang?: "fil" | "en";
};

let currentSound: Audio.Sound | null = null;
let lastStartAt = 0;
let playbackModeReady = false;
let lastRequestSignature = "";
let lastRequestAt = 0;

export async function stopSpeakLoud() {
  if (!currentSound) return;

  try {
    await currentSound.stopAsync();
  } catch {}

  try {
    await currentSound.unloadAsync();
  } catch {}

  currentSound = null;
}

async function forcePlaybackMode() {
  if (playbackModeReady) return;

  await Audio.setAudioModeAsync({
    allowsRecordingIOS: false,
    playsInSilentModeIOS: true,
    staysActiveInBackground: false,
    shouldDuckAndroid: false,
    playThroughEarpieceAndroid: false,
  });

  playbackModeReady = true;
}

export async function speakLoud(text: string, options?: VoiceOptions) {
  try {
    const cleanedText = (text || "").trim();
    if (!cleanedText) return;

    const now = Date.now();
    const signature = [
      cleanedText,
      options?.voice ?? "",
      options?.gender ?? "female",
      options?.style ?? "calm",
      options?.emphasis ?? "medium",
      String(options?.pauseMs ?? 280),
      options?.lang ?? "fil",
    ].join("|");

    // Generated by GitHub Copilot
    // Ignore rapid duplicate requests so active speech does not get interrupted.
    if (signature === lastRequestSignature && now - lastRequestAt < 1800) {
      if (__DEV__) {
        console.debug("[tts_loud] duplicate request ignored", {
          elapsedMs: now - lastRequestAt,
          preview: cleanedText.slice(0, 64),
        });
      }
      return;
    }

    // Generated by GitHub Copilot
    // Guard before stopSpeakLoud(): avoid cutting off current audio for near-simultaneous requests.
    if (now - lastStartAt < 250) {
      if (__DEV__) {
        console.debug("[tts_loud] throttled request ignored", {
          elapsedMs: now - lastStartAt,
          preview: cleanedText.slice(0, 64),
        });
      }
      return;
    }

    lastRequestSignature = signature;
    lastRequestAt = now;

    await stopSpeakLoud();
    lastStartAt = now;

    const voice = options?.voice;
    const gender = options?.gender ?? "female";
    const style = options?.style ?? "calm";
    const emphasis = options?.emphasis ?? "medium";
    const pauseMs = options?.pauseMs ?? 280;
    const volume = options?.volume ?? 1.0;
    const lang = options?.lang ?? "fil";

    const baseUrl =
      Constants.expoConfig?.extra?.API_BASE_URL ??
      "https://tara-ai-backend-swbp.onrender.com";

    const params = new URLSearchParams({
      lang,
      gender,
      style,
      emphasis,
      pause_ms: String(Math.max(80, Math.min(650, Math.round(pauseMs)))),
      text: cleanedText,
    });

    if (voice) {
      params.set("voice", voice);
    }

    const url = `${baseUrl}/tts?${params.toString()}`;

    if (__DEV__) {
      console.debug("[tts_loud] playback start", {
        preview: cleanedText.slice(0, 64),
      });
    }

    // very important for iPhone loud playback after recording
    await forcePlaybackMode();

    const { sound } = await Audio.Sound.createAsync(
      { uri: url },
      {
        shouldPlay: true,
        volume,
        progressUpdateIntervalMillis: 200,
      }
    );

    currentSound = sound;

    sound.setOnPlaybackStatusUpdate((status) => {
      const s: any = status;

      if (!s?.isLoaded) {
        if (s?.error) {
          console.warn("Audio playback error:", s.error);
        }
        return;
      }

      if (s.didJustFinish) {
        sound.unloadAsync().catch(() => {});
        if (currentSound === sound) currentSound = null;
      }
    });
  } catch (e) {
    console.warn("speakLoud failed:", e);
  }
}