import re

ACTION_TRANSLATIONS = {
    "head north": "dumiretso pahilaga",
    "head south": "dumiretso patimog",
    "head east": "dumiretso pasilangan",
    "head west": "dumiretso pakanluran",
    "continue": "magpatuloy",
    "keep left": "manatili sa kaliwa",
    "keep right": "manatili sa kanan",
    "turn left": "lumiko pakaliwa",
    "turn right": "lumiko pakanan",
    "slight left": "bahagyang lumiko pakaliwa",
    "slight right": "bahagyang lumiko pakanan",
    "make a u-turn": "mag-U-turn",
    "u-turn": "U-turn",
    "exit": "lumabas",
    "take the exit": "dumaan sa labasan",
    "merge": "sumanib sa daan",
    "destination will be on the left": "ang pupuntahan ay nasa kaliwa",
    "destination will be on the right": "ang pupuntahan ay nasa kanan",
    "you have arrived": "nakarating na tayo",
    "arrive": "dumating",
}

ACTION_PATTERN = re.compile(
    "|".join(sorted((re.escape(action) for action in ACTION_TRANSLATIONS.keys()), key=len, reverse=True)),
    flags=re.IGNORECASE,
)

DISTANCE_FIRST_PATTERNS = [
    re.compile(
        r"\b(?:in|after)\s+(?P<amount>\d+(?:\.\d+)?)\s*(?P<unit>meters?|meter|m|kilometers?|kilometer|km)\b[, ]*(?P<rest>.+)",
        flags=re.IGNORECASE,
    ),
    re.compile(
        r"^(?P<rest>.+?)\s+\b(?:in|after)\s+(?P<amount>\d+(?:\.\d+)?)\s*(?P<unit>meters?|meter|m|kilometers?|kilometer|km)\b",
        flags=re.IGNORECASE,
    ),
]


def _clean(s: str) -> str:
    s = re.sub(r"\s+", " ", s or "").strip()
    return s


def _distance_to_tagalog(amount: str, unit: str) -> str:
    """Convert metric distance snippets into Filipino-friendly phrasing."""
    value = float(amount)
    rendered = str(int(value)) if value.is_integer() else amount
    unit_value = unit.lower()
    if unit_value in {"km", "kilometer", "kilometers"}:
        return f"{rendered} kilometro"
    return f"{rendered} metro"


def _translate_actions(text: str) -> str:
    """Translate common imperative navigation verbs while preserving nearby road names."""
    return ACTION_PATTERN.sub(lambda match: ACTION_TRANSLATIONS[match.group(0).lower()], text)


def _expand_road_abbreviations(text: str) -> str:
    # Generated by GitHub Copilot
    """Expand common road suffix abbreviations so TTS pronounces them clearly."""
    text = re.sub(r"(\b[A-Za-z0-9]+)\s+St\.?(?=(?:\s|,|$))", r"\1 Street", text)
    text = re.sub(r"(\b[A-Za-z0-9]+)\s+Ave\.?(?=(?:\s|,|$))", r"\1 Avenue", text)
    text = re.sub(r"(\b[A-Za-z0-9]+)\s+Rd\.?(?=(?:\s|,|$))", r"\1 Road", text)
    text = re.sub(r"(\b[A-Za-z0-9]+)\s+Blvd\.?(?=(?:\s|,|$))", r"\1 Boulevard", text)
    text = re.sub(r"(\b[A-Za-z0-9]+)\s+Dr\.?(?=(?:\s|,|$))", r"\1 Drive", text)
    text = re.sub(r"(\b[A-Za-z0-9]+)\s+Ln\.?(?=(?:\s|,|$))", r"\1 Lane", text)
    text = re.sub(r"(\b[A-Za-z0-9]+)\s+Hwy\.?(?=(?:\s|,|$))", r"\1 Highway", text)
    text = re.sub(r"\bAve\.?(?=(?:\s|,|$))", "Avenue", text)
    text = re.sub(r"\bSt\.?(?=(?:\s|,|$))", "Street", text)
    return text


def _rewrite_distance_first(text: str) -> str:
    """Move distance cues to the front so instructions sound natural in Filipino."""
    for pattern in DISTANCE_FIRST_PATTERNS:
        match = pattern.search(text)
        if not match:
            continue

        rest = _translate_actions(match.group("rest").strip(" ,"))
        distance = _distance_to_tagalog(match.group("amount"), match.group("unit"))
        return f"Sa {distance}, {rest}"

    return text


def tagalog_rewrite(text: str) -> str:
    """
    Convert common English navigation phrases into smoother Filipino instructions.
    This keeps distance cues first, which sounds more natural for spoken guidance.
    """
    t = _clean(text)

    t = re.sub(r"<[^>]+>", "", t)
    t = t.replace("’", "'").replace("“", '"').replace("”", '"')
    t = _expand_road_abbreviations(t)

    t = _rewrite_distance_first(t)
    t = _translate_actions(t)

    repl = [
        (r"\bonto\b", "papunta sa"),
        (r"\btoward\b", "papunta sa"),
        (r"\bvia\b", "dumaan sa"),
        (r"^\bWalk\b", "Maglakad"),
        (r"^\bGo\b", "Pumunta"),
    ]

    for pattern, replacement in repl:
        t = re.sub(pattern, replacement, t, flags=re.IGNORECASE)

    t = _clean(t)

    if t and not t.endswith((".", "?", "!")):
        t += "."

    return t[:1].upper() + t[1:] if t else t


def tagalog_distance_phrase(meters: int) -> str:
    """Generate a natural Filipino lead-in for spoken distance alerts."""
    if meters < 15:
        return "Malapit na."
    return f"Sa {meters} metro,"
