# Generated by GitHub Copilot
from typing import Literal, Optional

from utils.tagalog_nav import tagalog_rewrite

VoiceStyle = Literal["calm", "warning"]
VoiceEmphasis = Literal["low", "medium", "high"]

VOICE_BY_GENDER = {
    "female": "nova",
    "male": "onyx",
}


def normalize_emphasis(emphasis: Optional[str]) -> VoiceEmphasis:
    """Clamp emphasis to the supported set so routes cannot pass arbitrary values through."""
    value = (emphasis or "medium").strip().lower()
    if value in {"low", "medium", "high"}:
        return value  # type: ignore[return-value]
    return "medium"


def normalize_pause_ms(pause_ms: Optional[int]) -> int:
    """Clamp pause duration to a safe range for TTS prosody shaping."""
    if pause_ms is None:
        return 280
    return max(80, min(int(pause_ms), 650))


def normalize_voice(voice: Optional[str], gender: Optional[str] = None) -> str:
    """Resolve raw OpenAI voice ids and simple gender aliases into a supported voice."""
    raw_voice = (voice or "").strip().lower()
    if raw_voice in {"female", "girl", "woman"}:
        return VOICE_BY_GENDER["female"]
    if raw_voice in {"male", "man", "boy"}:
        return VOICE_BY_GENDER["male"]
    if raw_voice:
        return raw_voice

    gender_key = (gender or "female").strip().lower()
    return VOICE_BY_GENDER.get(gender_key, VOICE_BY_GENDER["female"])


def _pause_separator(pause_ms: int) -> str:
    """Map pause duration to punctuation that nudges the speech model into longer pauses."""
    if pause_ms >= 420:
        return "... "
    if pause_ms >= 220:
        return ". "
    return ", "


def apply_style(text: str, style: VoiceStyle, pause_ms: int, emphasis: VoiceEmphasis) -> str:
    """Shape the opening cadence of navigation speech without changing route meaning."""
    body = (text or "").strip().rstrip(".?!")
    separator = _pause_separator(pause_ms)

    if style == "warning":
        if emphasis == "high":
            return f"Babala{separator}{body}. Mag-ingat agad."
        if emphasis == "low":
            return f"Babala, {body}."
        return f"Babala{separator}{body}. Mag-ingat."

    if emphasis == "high":
        return f"Makinig nang mabuti{separator}{body}."
    if emphasis == "low":
        return f"Makinig, {body}."
    return f"Makinig{separator}{body}."


def prepare_tts_text(
    text: str,
    lang: str = "fil",
    style: VoiceStyle = "calm",
    pause_ms: Optional[int] = None,
    emphasis: Optional[str] = None,
) -> tuple[str, int, VoiceEmphasis]:
    """Rewrite navigation text into smoother Filipino phrasing and then apply delivery shaping."""
    final_text = (text or "").strip()
    normalized_pause = normalize_pause_ms(pause_ms)
    normalized_emphasis = normalize_emphasis(emphasis)

    if (lang or "").lower().startswith("fil"):
        final_text = tagalog_rewrite(final_text)

    final_text = apply_style(final_text, style, normalized_pause, normalized_emphasis)
    return final_text, normalized_pause, normalized_emphasis